"use client";

import Link from "next/link";
import { useState } from "react";
import AdminShell, { PageHeader } from "../../components/admin-shell";

export default function GenerateReportPage() {
  const [generated, setGenerated] = useState(false);
  return <AdminShell title="Generate Report"><div className="page-content"><PageHeader eyebrow="REPORTS / NEW REPORT" title="Create a client report" description="Turn the latest SEO data into a polished update for your client." action={<Link className="secondary-button" href="/reports">← Reports</Link>} /><div className="report-builder"><section className="panel form-panel"><div className="form-section"><h2>Report setup</h2><p className="muted">Choose the client, period, and channels to include.</p><div className="form-grid"><label>Client<select defaultValue="Northstar Finance"><option>Northstar Finance</option><option>Morrow & Co.</option><option>Lumen Health</option></select></label><label>Reporting period<select defaultValue="Last 30 days"><option>Last 30 days</option><option>Last 90 days</option><option>Custom range</option></select></label><label className="wide">Report title<input defaultValue="Northstar Finance SEO performance report" /></label></div></div><div className="form-section"><h2>Include in report</h2><div className="report-checks"><label><input type="checkbox" defaultChecked /> Executive summary</label><label><input type="checkbox" defaultChecked /> Organic traffic from GA4</label><label><input type="checkbox" defaultChecked /> Search Console rankings</label><label><input type="checkbox" defaultChecked /> Site audit health</label><label><input type="checkbox" defaultChecked /> Backlinks</label><label><input type="checkbox" /> Competitor visibility</label></div></div><div className="form-footer"><button className="secondary-button">Save draft</button><button className="primary-button" onClick={() => setGenerated(true)}>{generated ? "Report generated ✓" : "Generate report"}</button></div></section><aside className="panel report-preview"><p className="eyebrow">LIVE PREVIEW</p><div className="preview-cover"><span className="brand-mark">s</span><small>SEO PERFORMANCE REPORT</small><h2>Northstar<br />Finance</h2><p>August 12 – September 10, 2026</p></div><div className="preview-data"><span><strong>184.2k</strong><small>Organic traffic</small></span><span><strong>2,846</strong><small>Keywords tracked</small></span><span><strong>92</strong><small>Health score</small></span></div><p className="muted">Data sources: Search Console · Google Analytics 4</p></aside></div></div></AdminShell>;
}
